vich_uploader:
    db_driver: orm
    mappings:
        post_image:
            uri_prefix: /uploads/images/posts
            upload_destination: '%kernel.project_dir%/public/uploads/images/posts'
            namer: vich_uploader.namer_origname
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
